import{a as q,S as E,i as s}from"./assets/vendor-S2qh7U4E.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const M="57070176-1d3ec272671065a7e5a57d0b3",R="https://pixabay.com/api/";async function g(r,e=1,i=15){return(await q.get(R,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:i}})).data}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more");let $=new E(".gallery a",{captionsData:"alt",captionDelay:250});function B(){h.innerHTML=""}function b(r){const e=r.map(({webformatURL:i,largeImageURL:a,tags:t,likes:o,views:n,comments:v,downloads:P})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${i}" alt="${t}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${o}</p>
        <p class="info-item"><b>Views</b> ${n}</p>
        <p class="info-item"><b>Comments</b> ${v}</p>
        <p class="info-item"><b>Downloads</b> ${P}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",e),$.refresh()}function L(){p.classList.remove("hidden")}function w(){p.classList.add("hidden")}function S(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}const f=document.querySelector(".form"),O=document.querySelector(".load-more");let c="",l=1;const d=15;let m=0;function x(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"})}f.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements.searchQuery.value.trim(),!c){s.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}l=1,B(),u(),L();try{const e=await g(c,l,d);if(m=e.totalHits,e.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(e.hits),m>d?S():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){s.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(e)}finally{w(),f.reset()}});O.addEventListener("click",async()=>{l+=1,u(),L();try{const r=await g(c,l,d);b(r.hits),x();const e=Math.ceil(m/d);l>=e?(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch(r){s.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(r)}finally{w()}});
//# sourceMappingURL=index.js.map
